import { useEffect, useState } from 'react'
import { Plus, Pencil } from 'lucide-react'
import { toast } from 'sonner'
import { api, Platform } from '../api'
import { SettingsBlock, SettingsActions } from './SettingsLayout'
export interface PlatformType { id: string; name: string }
interface Template { id: string; name: string; description: string; video: boolean; images: boolean; collect: boolean; fields: { key: string; label: string; type: string; default?: unknown }[] }
interface Draft { name: string; category: string; url: string; template: string; template_config: Record<string, unknown>; tags: string[]; enabled: boolean }
const fresh: Draft = { name: '', category: 'video', url: '', template: 'video_capture', template_config: {}, tags: [], enabled: true }
export function PlatformManager({ onChanged, onError }: { onChanged: () => Promise<void>; onError: (message: string) => void }) {
 const [items, setItems] = useState<Platform[]>([]), [types, setTypes] = useState<PlatformType[]>([]), [templates, setTemplates] = useState<Template[]>([])
 const [editing, setEditing] = useState<string | null>(null), [draft, setDraft] = useState<Draft>(fresh), [busy, setBusy] = useState(false), [tagText, setTagText] = useState('')
 const load = async () => { const [p,t,m] = await Promise.all([api<Platform[]>('/platforms?include_disabled=true'),api<PlatformType[]>('/platform-types'),api<Template[]>('/platform-templates')]);setItems(p.filter(v => v.id !== 'generic'));setTypes(t);setTemplates(m) }
 useEffect(() => { void load().catch(e => onError(e.message)) }, [])
 const template = templates.find(t => t.id === draft.template)
 const selectTemplate = (id: string) => { const value = templates.find(t => t.id === id);setDraft(old => ({ ...old, template: id, template_config: Object.fromEntries((value?.fields || []).map(f => [f.key, f.default ?? ''])) })) }
 const save = async () => { setBusy(true);try { await api(editing === 'new' ? '/platforms' : `/platforms/${editing}`,{...draft,tags:tagText.split(/[,，]/).map(v=>v.trim()).filter(Boolean)},editing === 'new' ? 'POST' : 'PUT');await load();await onChanged();setEditing(null);toast.success('平台配置已保存') } catch(e) { onError(e instanceof Error ? e.message : String(e)) } finally {setBusy(false)} }
 const archive = async (id:string) => {setBusy(true);try {await api(`/platforms/${id}`,undefined,'DELETE');await load();await onChanged();toast.success('平台已停用归档，历史任务仍然保留')}catch(e){onError(e instanceof Error ? e.message : String(e))}finally{setBusy(false)}}
 return <section className="wb-platform-manager">{editing===null&&<div className="wb-section-heading"><div><p>按网站类型管理入口，使用已实现的采集模板。</p></div><button onClick={() => {setDraft(fresh);setTagText('');setEditing('new')}}><Plus size={16}/>新增平台</button></div>}
  {editing !== null && <form className="wb-platform-editor wb-settings-form" onSubmit={e=>{e.preventDefault();void save()}}><h3>{editing === 'new' ? '新增平台' : '编辑平台'}</h3><SettingsBlock title="网站与入口" description="配置平台名称、分类与默认网址。"><div className="wb-settings-grid"><label>平台名称<input required maxLength={80} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>网站类型<select value={draft.category} onChange={e=>{ const category=e.target.value;const nextTemplate=['books','shopping'].includes(category)?'preview_only':draft.template;const value=templates.find(t=>t.id===nextTemplate);setDraft({...draft,category,template:nextTemplate,template_config:Object.fromEntries((value?.fields||[]).map(f=>[f.key,f.default??'']))}) }}>{types.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="wb-settings-full">网站入口<input required type="url" value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})} placeholder="https://example.com"/></label></div></SettingsBlock><SettingsBlock title="采集模板与规则" description="仅显示当前已实现的模板能力。"><div className="wb-settings-grid"><label>功能模板<select value={draft.template} onChange={e=>selectTemplate(e.target.value)}>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div><p className="wb-settings-note">{template?.description} {template && !template.collect && '仅提供网站预览；正文与价格等采集能力尚未接入。'}</p><div className="wb-settings-grid">{template?.fields.map(f=><label className={f.type === 'number' || f.type === 'integer' ? '':'wb-settings-full'} key={f.key}>{f.label}<input type={f.type === 'number' || f.type === 'integer' ? 'number':'text'} value={String(draft.template_config[f.key] ?? f.default ?? '')} onChange={e=>setDraft({...draft,template_config:{...draft.template_config,[f.key]:f.type === 'number' || f.type === 'integer'?Number(e.target.value):e.target.value}})}/></label>)}</div></SettingsBlock><SettingsBlock title="管理选项"><div className="wb-settings-grid"><label>标签（逗号分隔）<input value={tagText} onChange={e=>setTagText(e.target.value)}/></label><label className="wb-settings-toggle"><span>启用平台</span><input type="checkbox" checked={draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/></label></div></SettingsBlock><SettingsActions status="保存后更新平台配置，历史任务保持原定义"><button type="button" disabled={busy} onClick={()=>setEditing(null)}>取消编辑</button><button type="submit" className="wb-primary" disabled={busy}>{busy?'保存中…':'保存平台'}</button></SettingsActions></form>}
  {editing===null&&<div className="wb-platform-list">{items.map(p=><article className="wb-platform-row" key={p.id}><div><strong>{p.id === 'meishiwang'?'美石建工':p.name}</strong><div className="wb-tags"><span>{types.find(t=>t.id===p.category)?.name || '其他'}</span>{p.tags?.map(t=><span key={t}>{t}</span>)}<span>{p.builtin?'内置 · 只读':'自定义'}</span>{p.enabled === false && <span>已停用</span>}</div><p>{p.url}</p><small>{p.collect === false?'仅预览，采集能力待接入':p.video?'支持视频发现与采集':'支持平台内容采集'}</small></div>{!p.builtin && <div className="wb-platform-row-actions"><button disabled={busy} onClick={()=>{setEditing(p.id);setTagText((p.tags||[]).join(', '));setDraft({name:p.name,category:p.category||'other',url:p.url,template:p.template||'preview_only',template_config:p.template_config||{},tags:p.tags||[],enabled:p.enabled!==false})}}><Pencil size={15}/>编辑</button><button disabled={busy||p.enabled===false} onClick={()=>void archive(p.id)}>停用归档</button></div>}</article>)}</div>}
 </section>
}
